### PR TITLE
Fix `\text`

### LINKED ISSUE #62: `\text a` and `\operatorname a` are actually valid without the curly braces
It seems only `\begin{}` and `\end{}` really enforce them.

- [ ] `\text a`
- [x] `\operatorname a`

### LINKED ISSUE #94: There should be a whitespace token which is ignored except within `\text{...}`
It turns out that any whitespace (e.g., 7 spaces, 2 tabs, etc.) in `\text{...}` is just rendered as a single whitespace. This actually makes it a lot easier.

### PR DESCRIPTION
**Pull request by tmke8**
closes #62 
closes #94

### CODE REVIEW

File: latex2mmlc/src/parse.rs [hunk 1]
```diff
@@ -504,10 +504,17 @@ impl<'source> Parser<'source> {
...
+                self.l.record_whitespace = true;
+                let node = self.parse_single_token()?.as_node(&self.arena);
+                let start = self.buffer.end();
+                extract_letters(&self.arena, &mut self.buffer, node)?;
+                let end = self.buffer.end();
+                self.l.record_whitespace = false;
+                // Discard any whitespace tokens that are still stored in self.peek_token.
+                if matches!(self.peek_token, Token::NonBreakingSpace) {
+                    self.next_token();
+                }
```
Comment (tmke8) [inline latex2mmlc/src/parse.rs:516]: This shouldn't discard legitimate `~` tokens. So, I'll probably need to introduce a new token.

File: latex2mmlc/src/parse.rs [hunk 2]
```diff
@@ -763,6 +770,10 @@ fn extract_letters<'source>(
         Node::Operator(op, _) | Node::OperatorWithSpacing { op, .. } => {
             buffer.push(op.into());
         }
+        Node::Text(str_ref) => {
+            let string = str_ref.as_str(buffer).to_string();
+            buffer.push_str(string.as_str());
```
Comment (tmke8) [inline latex2mmlc/src/parse.rs:775]: I need [extend_from_within](https://doc.rust-lang.org/std/string/struct.String.html#method.extend_from_within) here, but that's night-only...

Comment (tmke8) [reply latex2mmlc/src/parse.rs:775]: I could have a while loop which takes a char and then pushes it to the end.

Comment (tmke8) [reply latex2mmlc/src/parse.rs:775]: Ah, I can use this trick:

```rust
    let mut s = String::from("Hello, world!");
    
    unsafe {
        let vec = s.as_mut_vec();
        vec.extend_from_within(0..5);
    }
```

**Comment by tmke8** [comment]
Important test case:

```tex
\text{x\text{y}}
```

File: latex2mmlc/src/parse.rs (hunk 2 above)
Comment (tmke8) [reply latex2mmlc/src/parse.rs:777]: This produces worse code, alas.
